spring:
  application:
    name: multi-agent-ecommerce
  ai:
    openai:
      api-key: sk-0Vx0aPGNlkinE0HBB7JEJr9MdlgGvYXOwWxi5pF3D0tj1d77
      base-url: https://api.chatanywhere.tech
      chat:
        options:
          model: gpt-5
          temperature: 0.7
  datasource:
    password: lf_MySQL
    username: root
    url: jdbc:mysql://localhost:3306/multi_agent?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
